<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>peso seco final</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="peso_seco_final_files/libs/clipboard/clipboard.min.js"></script>
<script src="peso_seco_final_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="peso_seco_final_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="peso_seco_final_files/libs/quarto-html/popper.min.js"></script>
<script src="peso_seco_final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="peso_seco_final_files/libs/quarto-html/anchor.min.js"></script>
<link href="peso_seco_final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="peso_seco_final_files/libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="peso_seco_final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="peso_seco_final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="peso_seco_final_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">peso seco final</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|label: setup</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>peso<span class="ot">&lt;-</span>data.table<span class="sc">::</span><span class="fu">data.table</span>(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">Tratamiento =</span> <span class="fu">c</span>(<span class="st">"Glifosato"</span>,<span class="st">"Glifosato"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Glifosato"</span>,<span class="st">"Glifosato"</span>,<span class="st">"Glifosato"</span>,<span class="st">"Glifosato"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Glifosato"</span>,<span class="st">"Glifosato"</span>,<span class="st">"2,4D"</span>,<span class="st">"2,4D"</span>,<span class="st">"2,4D"</span>,<span class="st">"2,4D"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"2,4D"</span>,<span class="st">"2,4D"</span>,<span class="st">"2,4D"</span>,<span class="st">"2,4D"</span>,<span class="st">"Dicamba"</span>,<span class="st">"Dicamba"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Dicamba"</span>,<span class="st">"Dicamba"</span>,<span class="st">"Dicamba"</span>,<span class="st">"Dicamba"</span>,<span class="st">"Dicamba"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Dicamba"</span>,<span class="st">"Imazetapir"</span>,<span class="st">"Imazetapir"</span>,<span class="st">"Imazetapir"</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Imazetapir"</span>,<span class="st">"Imazetapir"</span>,<span class="st">"Imazetapir"</span>,<span class="st">"Imazetapir"</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Imazetapir"</span>,<span class="st">"Clorimuron"</span>,<span class="st">"Clorimuron"</span>,<span class="st">"Clorimuron"</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Clorimuron"</span>,<span class="st">"Clorimuron"</span>,<span class="st">"Clorimuron"</span>,<span class="st">"Clorimuron"</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Clorimuron"</span>,<span class="st">"Testigo"</span>,<span class="st">"Testigo"</span>,<span class="st">"Testigo"</span>,<span class="st">"Testigo"</span>,<span class="st">"Testigo"</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Testigo"</span>,<span class="st">"Testigo"</span>,<span class="st">"Testigo"</span>),</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">Maceta =</span> <span class="fu">c</span>(<span class="dv">1</span>L,<span class="dv">2</span>L,<span class="dv">3</span>L,<span class="dv">4</span>L,<span class="dv">5</span>L,<span class="dv">6</span>L,<span class="dv">7</span>L,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>                        <span class="dv">8</span>L,<span class="dv">1</span>L,<span class="dv">2</span>L,<span class="dv">3</span>L,<span class="dv">4</span>L,<span class="dv">5</span>L,<span class="dv">6</span>L,<span class="dv">7</span>L,<span class="dv">8</span>L,<span class="dv">1</span>L,<span class="dv">2</span>L,<span class="dv">3</span>L,<span class="dv">4</span>L,<span class="dv">5</span>L,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>                        <span class="dv">6</span>L,<span class="dv">7</span>L,<span class="dv">8</span>L,<span class="dv">1</span>L,<span class="dv">2</span>L,<span class="dv">3</span>L,<span class="dv">4</span>L,<span class="dv">5</span>L,<span class="dv">6</span>L,<span class="dv">7</span>L,<span class="dv">8</span>L,<span class="dv">1</span>L,<span class="dv">2</span>L,<span class="dv">3</span>L,</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>                        <span class="dv">4</span>L,<span class="dv">5</span>L,<span class="dv">6</span>L,<span class="dv">7</span>L,<span class="dv">8</span>L,<span class="dv">1</span>L,<span class="dv">2</span>L,<span class="dv">3</span>L,<span class="dv">4</span>L,<span class="dv">5</span>L,<span class="dv">6</span>L,<span class="dv">7</span>L,<span class="dv">8</span>L),</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>          <span class="at">Condicion =</span> <span class="fu">c</span>(<span class="st">"Sin estres"</span>,<span class="st">"Sin estres"</span>,</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Sin estres"</span>,<span class="st">"Sin estres"</span>,<span class="st">"Con estres"</span>,<span class="st">"Con estres"</span>,</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Con estres"</span>,<span class="st">"Con estres"</span>,<span class="st">"Sin estres"</span>,<span class="st">"Sin estres"</span>,</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Sin estres"</span>,<span class="st">"Sin estres"</span>,<span class="st">"Con estres"</span>,<span class="st">"Con estres"</span>,</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Con estres"</span>,<span class="st">"Con estres"</span>,<span class="st">"Sin estres"</span>,<span class="st">"Sin estres"</span>,</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Sin estres"</span>,<span class="st">"Sin estres"</span>,<span class="st">"Con estres"</span>,<span class="st">"Con estres"</span>,</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Con estres"</span>,<span class="st">"Con estres"</span>,<span class="st">"Sin estres"</span>,<span class="st">"Sin estres"</span>,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Sin estres"</span>,<span class="st">"Sin estres"</span>,<span class="st">"Con estres"</span>,<span class="st">"Con estres"</span>,</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Con estres"</span>,<span class="st">"Con estres"</span>,<span class="st">"Sin estres"</span>,<span class="st">"Sin estres"</span>,</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Sin estres"</span>,<span class="st">"Sin estres"</span>,<span class="st">"Con estres"</span>,<span class="st">"Con estres"</span>,</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Con estres"</span>,<span class="st">"Con estres"</span>,<span class="st">"Sin estres"</span>,<span class="st">"Sin estres"</span>,</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Sin estres"</span>,<span class="st">"Sin estres"</span>,<span class="st">"Con estres"</span>,<span class="st">"Con estres"</span>,</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"Con estres"</span>,<span class="st">"Con estres"</span>),</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>             <span class="at">Numero =</span> <span class="fu">c</span>(<span class="dv">6</span>L,<span class="dv">4</span>L,<span class="dv">7</span>L,<span class="dv">6</span>L,<span class="dv">3</span>L,<span class="dv">9</span>L,<span class="dv">4</span>L,</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>                        <span class="dv">3</span>L,<span class="dv">7</span>L,<span class="dv">4</span>L,<span class="dv">6</span>L,<span class="dv">6</span>L,<span class="dv">9</span>L,<span class="dv">3</span>L,<span class="dv">7</span>L,<span class="dv">6</span>L,<span class="dv">5</span>L,<span class="dv">4</span>L,<span class="dv">2</span>L,<span class="dv">3</span>L,<span class="dv">4</span>L,</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>                        <span class="dv">4</span>L,<span class="dv">6</span>L,<span class="dv">5</span>L,<span class="dv">4</span>L,<span class="dv">6</span>L,<span class="dv">6</span>L,<span class="dv">6</span>L,<span class="dv">5</span>L,<span class="dv">8</span>L,<span class="dv">6</span>L,<span class="dv">5</span>L,<span class="dv">6</span>L,<span class="dv">4</span>L,<span class="dv">6</span>L,</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>                        <span class="dv">4</span>L,<span class="dv">6</span>L,<span class="dv">3</span>L,<span class="dv">5</span>L,<span class="dv">6</span>L,<span class="dv">3</span>L,<span class="dv">7</span>L,<span class="dv">4</span>L,<span class="dv">5</span>L,<span class="dv">7</span>L,<span class="dv">8</span>L,<span class="dv">6</span>L,<span class="dv">7</span>L),</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>               <span class="at">Peso =</span> <span class="fu">c</span>(<span class="fl">0.0553</span>,<span class="fl">0.0337</span>,<span class="fl">0.1004</span>,</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>                        <span class="fl">0.0957</span>,<span class="fl">0.0161</span>,<span class="fl">0.0413</span>,<span class="fl">0.0236</span>,<span class="fl">0.0312</span>,<span class="fl">0.0721</span>,<span class="fl">0.0351</span>,</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>                        <span class="fl">0.0711</span>,<span class="fl">0.0986</span>,<span class="fl">0.0449</span>,<span class="fl">0.0253</span>,<span class="fl">0.036</span>,<span class="fl">0.0307</span>,<span class="fl">0.0393</span>,<span class="fl">0.0534</span>,</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>                        <span class="fl">0.0442</span>,<span class="fl">0.058</span>,<span class="fl">0.0295</span>,<span class="fl">0.0252</span>,<span class="fl">0.0397</span>,<span class="fl">0.0483</span>,<span class="fl">0.0548</span>,</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>                        <span class="fl">0.0724</span>,<span class="fl">0.0877</span>,<span class="fl">0.0971</span>,<span class="fl">0.0377</span>,<span class="fl">0.0351</span>,<span class="fl">0.0711</span>,<span class="fl">0.0419</span>,</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>                        <span class="fl">0.0924</span>,<span class="fl">0.0575</span>,<span class="fl">0.1003</span>,<span class="fl">0.0552</span>,<span class="fl">0.0505</span>,<span class="fl">0.0284</span>,<span class="fl">0.041</span>,</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>                        <span class="fl">0.0419</span>,<span class="fl">0.0494</span>,<span class="fl">0.0815</span>,<span class="fl">0.1109</span>,<span class="fl">0.0451</span>,<span class="fl">0.0473</span>,<span class="fl">0.0651</span>,</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>                        <span class="fl">0.0324</span>,<span class="fl">0.0427</span>)</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>      )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>resumen <span class="ot">&lt;-</span> peso <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Tratamiento, Condicion) <span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">mediana =</span><span class="fu">round</span>(<span class="fu">median</span>(Peso, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),<span class="dv">3</span>) ,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">round</span>(<span class="fu">mean</span>(Peso, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),<span class="dv">3</span>),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">round</span>(<span class="fu">sd</span>(Peso, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),<span class="dv">3</span>),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">error_estandar =</span> <span class="fu">round</span>(sd <span class="sc">/</span> <span class="fu">sqrt</span>(n),<span class="dv">3</span>),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(Peso, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(Peso, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Tratamiento'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>resumen</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 9
# Groups:   Tratamiento [6]
   Tratamiento Condicion      n mediana media    sd error_estandar    min    max
   &lt;chr&gt;       &lt;chr&gt;      &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;          &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 2,4D        Con estres     4   0.033 0.034 0.008          0.004 0.0253 0.0449
 2 2,4D        Sin estres     4   0.072 0.069 0.026          0.013 0.0351 0.0986
 3 Clorimuron  Con estres     4   0.041 0.04  0.009          0.004 0.0284 0.0505
 4 Clorimuron  Sin estres     4   0.075 0.076 0.023          0.012 0.0552 0.100 
 5 Dicamba     Con estres     4   0.035 0.036 0.01           0.005 0.0252 0.0483
 6 Dicamba     Sin estres     4   0.049 0.049 0.009          0.004 0.0393 0.058 
 7 Glifosato   Con estres     4   0.027 0.028 0.011          0.005 0.0161 0.0413
 8 Glifosato   Sin estres     4   0.076 0.071 0.032          0.016 0.0337 0.100 
 9 Imazetapir  Con estres     4   0.04  0.046 0.017          0.009 0.0351 0.0711
10 Imazetapir  Sin estres     4   0.08  0.078 0.019          0.01  0.0548 0.0971
11 Testigo     Con estres     4   0.045 0.047 0.014          0.007 0.0324 0.0651
12 Testigo     Sin estres     4   0.065 0.072 0.031          0.016 0.0451 0.111 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#grafico de interaccion</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>g_interaccion<span class="ot">&lt;-</span><span class="fu">ggplot</span>(peso, <span class="fu">aes</span>(<span class="at">x =</span> Tratamiento, <span class="at">y =</span> Peso, <span class="at">color =</span> Condicion, <span class="at">group =</span> Condicion)) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># puntos (medias)</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># líneas de interacción</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># barras de error (opcional pero MUY recomendable)</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Gráfico de interacción: Condición × Tratamiento"</span>,</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Tratamiento"</span>,</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Peso promedio"</span>,</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Condición"</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>g_interaccion</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="peso_seco_final_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># guardo grafico de interaccion</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"C:/Users/USUARIO/Desktop/copia de seguridad/trabajo/trabajo/consultorias/consultorias 2025/Nicolás Sposito/c_n_exposito_posmergencia/graficos/grafico interacción.png"</span>,g_interaccion,  <span class="at">width =</span><span class="dv">12</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">height =</span> <span class="dv">10</span>,<span class="at">bg =</span> <span class="st">"white"</span>,<span class="at">dpi =</span> <span class="dv">300</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="anova-factorial" class="level2">
<h2 class="anchored" data-anchor-id="anova-factorial">Anova factorial</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">aov</span>(Peso <span class="sc">~</span> Condicion <span class="sc">*</span> Tratamiento, <span class="at">data =</span> peso)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      Df   Sum Sq  Mean Sq F value   Pr(&gt;F)    
Condicion              1 0.011233 0.011233  30.200 3.28e-06 ***
Tratamiento            5 0.002226 0.000445   1.197    0.330    
Condicion:Tratamiento  5 0.001098 0.000220   0.590    0.707    
Residuals             36 0.013391 0.000372                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograma</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="peso_seco_final_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># QQ plot</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(res)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="peso_seco_final_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Shapiro</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  res
W = 0.99244, p-value = 0.9883</code></pre>
</div>
</div>
<p>Se cumple la normalidad</p>
</section>
<section id="homcedasticidad" class="level2">
<h2 class="anchored" data-anchor-id="homcedasticidad">Homcedasticidad</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo, <span class="dv">1</span>)  <span class="co"># residuos vs ajustados</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="peso_seco_final_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(Peso <span class="sc">~</span> Tratamiento <span class="sc">*</span> Condicion, <span class="at">data =</span> peso)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value  Pr(&gt;F)  
group 11  2.2767 0.03117 *
      36                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="falta-de-homocedasticidad" class="level4">
<h4 class="anchored" data-anchor-id="falta-de-homocedasticidad">Falta de homocedasticidad</h4>
<p>El análisis gráfico de los residuos en función de los valores ajustados evidenció un patrón de dispersión creciente, indicando la presencia de heterocedasticidad. Por lo tanto, no se cumple el supuesto de homogeneidad de varianzas requerido por el ANOVA. tambien se obtiene un p valore de 0.03117 en el test de hocedasticidad</p>
<p>Se debe incorporar en el modelo</p>
</section>
</section>
<section id="modelo-por-medio-de-medio-de-gls" class="level2">
<h2 class="anchored" data-anchor-id="modelo-por-medio-de-medio-de-gls">Modelo por medio de medio de gls</h2>
<section id="solo-varianza-heterocedasticas-en-los-tratamientos" class="level3">
<h3 class="anchored" data-anchor-id="solo-varianza-heterocedasticas-en-los-tratamientos">Solo varianza heterocedasticas en los tratamientos</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'nlme'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    collapse</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>modelo_gls <span class="ot">&lt;-</span> <span class="fu">gls</span>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  Peso <span class="sc">~</span> Tratamiento <span class="sc">*</span> Condicion,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> Tratamiento),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> peso</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_gls)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: Peso ~ Tratamiento * Condicion 
  Data: peso 
        AIC       BIC   logLik
  -134.9015 -106.3982 85.45076

Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | Tratamiento 
 Parameter estimates:
 Glifosato       2,4D    Dicamba Imazetapir Clorimuron    Testigo 
 1.0000000  0.8061102  0.3952868  0.7336253  0.7376061  0.9908243 

Coefficients:
                                              Value   Std.Error   t-value
(Intercept)                                0.034225 0.009678949  3.536024
TratamientoClorimuron                      0.006225 0.013119385  0.474489
TratamientoDicamba                         0.001450 0.010780004  0.134508
TratamientoGlifosato                      -0.006175 0.015422375 -0.400392
TratamientoImazetapir                      0.012225 0.013087167  0.934121
TratamientoTestigo                         0.012650 0.015336757  0.824816
CondicionSin estres                        0.035000 0.013688101  2.556965
TratamientoClorimuron:CondicionSin estres  0.000900 0.018553612  0.048508
TratamientoDicamba:CondicionSin estres    -0.021950 0.015245227 -1.439795
TratamientoGlifosato:CondicionSin estres   0.008225 0.021810531  0.377111
TratamientoImazetapir:CondicionSin estres -0.003450 0.018508049 -0.186405
TratamientoTestigo:CondicionSin estres    -0.010150 0.021689450 -0.467969
                                          p-value
(Intercept)                                0.0011
TratamientoClorimuron                      0.6380
TratamientoDicamba                         0.8937
TratamientoGlifosato                       0.6912
TratamientoImazetapir                      0.3565
TratamientoTestigo                         0.4149
CondicionSin estres                        0.0149
TratamientoClorimuron:CondicionSin estres  0.9616
TratamientoDicamba:CondicionSin estres     0.1586
TratamientoGlifosato:CondicionSin estres   0.7083
TratamientoImazetapir:CondicionSin estres  0.8532
TratamientoTestigo:CondicionSin estres     0.6426

 Correlation: 
                                          (Intr) TrtmnC TrtmnD TrtmnG TrtmnI
TratamientoClorimuron                     -0.738                            
TratamientoDicamba                        -0.898  0.662                     
TratamientoGlifosato                      -0.628  0.463  0.563              
TratamientoImazetapir                     -0.740  0.546  0.664  0.464       
TratamientoTestigo                        -0.631  0.466  0.567  0.396  0.467
CondicionSin estres                       -0.707  0.522  0.635  0.444  0.523
TratamientoClorimuron:CondicionSin estres  0.522 -0.707 -0.468 -0.327 -0.386
TratamientoDicamba:CondicionSin estres     0.635 -0.468 -0.707 -0.398 -0.470
TratamientoGlifosato:CondicionSin estres   0.444 -0.327 -0.398 -0.707 -0.328
TratamientoImazetapir:CondicionSin estres  0.523 -0.386 -0.470 -0.328 -0.707
TratamientoTestigo:CondicionSin estres     0.446 -0.329 -0.401 -0.280 -0.330
                                          TrtmnT CndcSe TC:CSe TD:CSe TG:CSe
TratamientoClorimuron                                                       
TratamientoDicamba                                                          
TratamientoGlifosato                                                        
TratamientoImazetapir                                                       
TratamientoTestigo                                                          
CondicionSin estres                        0.446                            
TratamientoClorimuron:CondicionSin estres -0.329 -0.738                     
TratamientoDicamba:CondicionSin estres    -0.401 -0.898  0.662              
TratamientoGlifosato:CondicionSin estres  -0.280 -0.628  0.463  0.563       
TratamientoImazetapir:CondicionSin estres -0.330 -0.740  0.546  0.664  0.464
TratamientoTestigo:CondicionSin estres    -0.707 -0.631  0.466  0.567  0.396
                                          TI:CSe
TratamientoClorimuron                           
TratamientoDicamba                              
TratamientoGlifosato                            
TratamientoImazetapir                           
TratamientoTestigo                              
CondicionSin estres                             
TratamientoClorimuron:CondicionSin estres       
TratamientoDicamba:CondicionSin estres          
TratamientoGlifosato:CondicionSin estres        
TratamientoImazetapir:CondicionSin estres       
TratamientoTestigo:CondicionSin estres     0.467

Standardized residuals:
        Min          Q1         Med          Q3         Max 
-1.76284634 -0.64582126  0.02445642  0.55566800  1.64644996 

Residual standard error: 0.02401396 
Degrees of freedom: 48 total; 36 residual</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo_gls)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Denom. DF: 36 
                      numDF  F-value p-value
(Intercept)               1 473.5623  &lt;.0001
Tratamiento               5   2.4681  0.0507
Condicion                 1  27.7501  &lt;.0001
Tratamiento:Condicion     5   1.1719  0.3419</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo_gls, <span class="at">type =</span> <span class="st">"normalized"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">fitted</span>(modelo_gls)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit, res)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="peso_seco_final_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(res)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="peso_seco_final_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  res
W = 0.9779, p-value = 0.4946</code></pre>
</div>
</div>
</section>
<section id="varianza-heterocedasticas-en-los-tratamientos-y-condición" class="level3">
<h3 class="anchored" data-anchor-id="varianza-heterocedasticas-en-los-tratamientos-y-condición">varianza heterocedasticas en los tratamientos y condición</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>modelo_gls2 <span class="ot">&lt;-</span> <span class="fu">gls</span>(</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  Peso <span class="sc">~</span> Tratamiento <span class="sc">*</span> Condicion,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span><span class="dv">1</span> <span class="sc">|</span> Tratamiento <span class="sc">*</span> Condicion),</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> peso</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_gls2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized least squares fit by REML
  Model: Peso ~ Tratamiento * Condicion 
  Data: peso 
        AIC       BIC   logLik
  -133.4919 -95.48746 90.74596

Variance function:
 Structure: Different standard deviations per stratum
 Formula: ~1 | Tratamiento * Condicion 
 Parameter estimates:
 Glifosato*Sin estres  Glifosato*Con estres       2,4D*Sin estres 
            1.0000000             0.3344535             0.8095028 
      2,4D*Con estres    Dicamba*Sin estres    Dicamba*Con estres 
            0.2592728             0.2641841             0.3223973 
Imazetapir*Sin estres Imazetapir*Con estres Clorimuron*Sin estres 
            0.5749007             0.5176025             0.7245977 
Clorimuron*Con estres    Testigo*Sin estres    Testigo*Con estres 
            0.2826495             0.9549045             0.4239438 

Coefficients:
                                              Value   Std.Error   t-value
(Intercept)                                0.034225 0.004175197  8.197219
TratamientoClorimuron                      0.006225 0.006176547  1.007845
TratamientoDicamba                         0.001450 0.006662299  0.217643
TratamientoGlifosato                      -0.006175 0.006814678 -0.906132
TratamientoImazetapir                      0.012225 0.009322443  1.311352
TratamientoTestigo                         0.012650 0.008002490  1.580758
CondicionSin estres                        0.035000 0.013688128  2.556960
TratamientoClorimuron:CondicionSin estres  0.000900 0.018553635  0.048508
TratamientoDicamba:CondicionSin estres    -0.021950 0.015245254 -1.439792
TratamientoGlifosato:CondicionSin estres   0.008225 0.021810428  0.377113
TratamientoImazetapir:CondicionSin estres -0.003450 0.018508089 -0.186405
TratamientoTestigo:CondicionSin estres    -0.010150 0.021689481 -0.467969
                                          p-value
(Intercept)                                0.0000
TratamientoClorimuron                      0.3203
TratamientoDicamba                         0.8289
TratamientoGlifosato                       0.3709
TratamientoImazetapir                      0.1980
TratamientoTestigo                         0.1227
CondicionSin estres                        0.0149
TratamientoClorimuron:CondicionSin estres  0.9616
TratamientoDicamba:CondicionSin estres     0.1586
TratamientoGlifosato:CondicionSin estres   0.7083
TratamientoImazetapir:CondicionSin estres  0.8532
TratamientoTestigo:CondicionSin estres     0.6426

 Correlation: 
                                          (Intr) TrtmnC TrtmnD TrtmnG TrtmnI
TratamientoClorimuron                     -0.676                            
TratamientoDicamba                        -0.627  0.424                     
TratamientoGlifosato                      -0.613  0.414  0.384              
TratamientoImazetapir                     -0.448  0.303  0.281  0.274       
TratamientoTestigo                        -0.522  0.353  0.327  0.320  0.234
CondicionSin estres                       -0.305  0.206  0.191  0.187  0.137
TratamientoClorimuron:CondicionSin estres  0.225 -0.333 -0.141 -0.138 -0.101
TratamientoDicamba:CondicionSin estres     0.274 -0.185 -0.437 -0.168 -0.123
TratamientoGlifosato:CondicionSin estres   0.191 -0.129 -0.120 -0.312 -0.086
TratamientoImazetapir:CondicionSin estres  0.226 -0.152 -0.141 -0.138 -0.504
TratamientoTestigo:CondicionSin estres     0.192 -0.130 -0.121 -0.118 -0.086
                                          TrtmnT CndcSe TC:CSe TD:CSe TG:CSe
TratamientoClorimuron                                                       
TratamientoDicamba                                                          
TratamientoGlifosato                                                        
TratamientoImazetapir                                                       
TratamientoTestigo                                                          
CondicionSin estres                        0.159                            
TratamientoClorimuron:CondicionSin estres -0.117 -0.738                     
TratamientoDicamba:CondicionSin estres    -0.143 -0.898  0.662              
TratamientoGlifosato:CondicionSin estres  -0.100 -0.628  0.463  0.563       
TratamientoImazetapir:CondicionSin estres -0.118 -0.740  0.546  0.664  0.464
TratamientoTestigo:CondicionSin estres    -0.369 -0.631  0.466  0.567  0.396
                                          TI:CSe
TratamientoClorimuron                           
TratamientoDicamba                              
TratamientoGlifosato                            
TratamientoImazetapir                           
TratamientoTestigo                              
CondicionSin estres                             
TratamientoClorimuron:CondicionSin estres       
TratamientoDicamba:CondicionSin estres          
TratamientoGlifosato:CondicionSin estres        
TratamientoImazetapir:CondicionSin estres       
TratamientoTestigo:CondicionSin estres     0.467

Standardized residuals:
        Min          Q1         Med          Q3         Max 
-1.32369761 -0.74636266  0.04577213  0.79485882  1.47866761 

Residual standard error: 0.03220698 
Degrees of freedom: 48 total; 36 residual</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo_gls2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Denom. DF: 36 
                      numDF  F-value p-value
(Intercept)               1 563.4380  &lt;.0001
Tratamiento               5   3.2369  0.0163
Condicion                 1  27.7501  &lt;.0001
Tratamiento:Condicion     5   1.1719  0.3419</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>res2 <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo_gls2, <span class="at">type =</span> <span class="st">"normalized"</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">fitted</span>(modelo_gls2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit2, res2)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="peso_seco_final_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(res2)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(res2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="peso_seco_final_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(res2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  res2
W = 0.93281, p-value = 0.00867</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>modelo_gls0 <span class="ot">&lt;-</span> <span class="fu">gls</span>(</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  Peso <span class="sc">~</span> Tratamiento <span class="sc">*</span> Condicion,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> peso</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo_gls0, modelo_gls,modelo_gls2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            df       AIC
modelo_gls0 13 -139.4831
modelo_gls  18 -134.9015
modelo_gls2 24 -133.4919</code></pre>
</div>
</div>
<p>Aunque el model sin modelara varianza es sensiblemente mejor que los otros en función de AIC, se debe tener en cuenta la heterocedasticidad</p>
<p>me quedo con el modelo con hetercedasticidad en los tratamientos, el modelo ajusta mejor</p>
<p>El modelo tien un valor limite de p para tratamientos, por las dudas hago uno prueba de medias para tratamientos</p>
</section>
</section>
<section id="comparo-medias" class="level2">
<h2 class="anchored" data-anchor-id="comparo-medias">Comparo medias</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>emm_trat <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(modelo_gls, <span class="sc">~</span> Tratamiento)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>NOTE: Results may be misleading due to involvement in interactions</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>emm_trat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Tratamiento emmean      SE   df lower.CL upper.CL
 2,4D        0.0517 0.00684 6.00   0.0350   0.0685
 Clorimuron  0.0584 0.00626 6.00   0.0431   0.0737
 Dicamba     0.0422 0.00336 6.00   0.0340   0.0504
 Glifosato   0.0497 0.00849 5.99   0.0289   0.0704
 Imazetapir  0.0622 0.00623 6.00   0.0470   0.0775
 Testigo     0.0593 0.00841 6.12   0.0388   0.0798

Results are averaged over the levels of: Condicion 
Degrees-of-freedom method: satterthwaite 
Confidence level used: 0.95 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(emm_trat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                estimate      SE    df t.ratio p.value
 2,4D - Clorimuron       -0.00668 0.00928 11.91  -0.720  0.9757
 2,4D - Dicamba           0.00953 0.00762  8.73   1.250  0.8034
 2,4D - Glifosato         0.00206 0.01090 11.49   0.189  1.0000
 2,4D - Imazetapir       -0.01050 0.00925 11.89  -1.135  0.8579
 2,4D - Testigo          -0.00758 0.01080 11.65  -0.698  0.9785
 Clorimuron - Dicamba     0.01620 0.00711  9.18   2.280  0.2905
 Clorimuron - Glifosato   0.00874 0.01050 11.03   0.828  0.9559
 Clorimuron - Imazetapir -0.00382 0.00883 12.00  -0.433  0.9976
 Clorimuron - Testigo    -0.00090 0.01050 11.24  -0.086  1.0000
 Dicamba - Glifosato     -0.00746 0.00913  7.82  -0.817  0.9558
 Dicamba - Imazetapir    -0.02003 0.00708  9.21  -2.830  0.1377
 Dicamba - Testigo       -0.01710 0.00906  8.02  -1.888  0.4694
 Glifosato - Imazetapir  -0.01256 0.01050 11.04  -1.193  0.8315
 Glifosato - Testigo     -0.00964 0.01200 12.01  -0.806  0.9609
 Imazetapir - Testigo     0.00293 0.01050 11.17   0.279  0.9997

Results are averaged over the levels of: Condicion 
Degrees-of-freedom method: satterthwaite 
P value adjustment: tukey method for comparing a family of 6 estimates </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(emm_trat, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                estimate      SE    df t.ratio p.value
 2,4D - Clorimuron       -0.00668 0.00928 11.91  -0.720  0.9757
 2,4D - Dicamba           0.00953 0.00762  8.73   1.250  0.8034
 2,4D - Glifosato         0.00206 0.01090 11.49   0.189  1.0000
 2,4D - Imazetapir       -0.01050 0.00925 11.89  -1.135  0.8579
 2,4D - Testigo          -0.00758 0.01080 11.65  -0.698  0.9785
 Clorimuron - Dicamba     0.01620 0.00711  9.18   2.280  0.2905
 Clorimuron - Glifosato   0.00874 0.01050 11.03   0.828  0.9559
 Clorimuron - Imazetapir -0.00382 0.00883 12.00  -0.433  0.9976
 Clorimuron - Testigo    -0.00090 0.01050 11.24  -0.086  1.0000
 Dicamba - Glifosato     -0.00746 0.00913  7.82  -0.817  0.9558
 Dicamba - Imazetapir    -0.02003 0.00708  9.21  -2.830  0.1377
 Dicamba - Testigo       -0.01710 0.00906  8.02  -1.888  0.4694
 Glifosato - Imazetapir  -0.01256 0.01050 11.04  -1.193  0.8315
 Glifosato - Testigo     -0.00964 0.01200 12.01  -0.806  0.9609
 Imazetapir - Testigo     0.00293 0.01050 11.17   0.279  0.9997

Results are averaged over the levels of: Condicion 
Degrees-of-freedom method: satterthwaite 
P value adjustment: tukey method for comparing a family of 6 estimates </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>emm_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(emm_trat)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(emm_df, <span class="fu">aes</span>(<span class="at">x =</span> Tratamiento, <span class="at">y =</span> emmean)) <span class="sc">+</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lower.CL, <span class="at">ymax =</span> upper.CL), <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Peso medio estimado"</span>,</span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Tratamiento"</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="peso_seco_final_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>emm_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(emm_trat)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(emm_df, <span class="fu">aes</span>(<span class="at">x =</span> Tratamiento, <span class="at">y =</span> emmean)) <span class="sc">+</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lower.CL, <span class="at">ymax =</span> upper.CL), <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Peso medio estimado"</span>,</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Tratamiento"</span></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="peso_seco_final_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(emm_trat, <span class="at">adjust =</span> <span class="st">"bonferroni"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                estimate      SE    df t.ratio p.value
 2,4D - Clorimuron       -0.00668 0.00928 11.91  -0.720  1.0000
 2,4D - Dicamba           0.00953 0.00762  8.73   1.250  1.0000
 2,4D - Glifosato         0.00206 0.01090 11.49   0.189  1.0000
 2,4D - Imazetapir       -0.01050 0.00925 11.89  -1.135  1.0000
 2,4D - Testigo          -0.00758 0.01080 11.65  -0.698  1.0000
 Clorimuron - Dicamba     0.01620 0.00711  9.18   2.280  0.7201
 Clorimuron - Glifosato   0.00874 0.01050 11.03   0.828  1.0000
 Clorimuron - Imazetapir -0.00382 0.00883 12.00  -0.433  1.0000
 Clorimuron - Testigo    -0.00090 0.01050 11.24  -0.086  1.0000
 Dicamba - Glifosato     -0.00746 0.00913  7.82  -0.817  1.0000
 Dicamba - Imazetapir    -0.02003 0.00708  9.21  -2.830  0.2891
 Dicamba - Testigo       -0.01710 0.00906  8.02  -1.888  1.0000
 Glifosato - Imazetapir  -0.01256 0.01050 11.04  -1.193  1.0000
 Glifosato - Testigo     -0.00964 0.01200 12.01  -0.806  1.0000
 Imazetapir - Testigo     0.00293 0.01050 11.17   0.279  1.0000

Results are averaged over the levels of: Condicion 
Degrees-of-freedom method: satterthwaite 
P value adjustment: bonferroni method for 15 tests </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(emm_trat, <span class="at">adjust =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                estimate      SE    df t.ratio p.value
 2,4D - Clorimuron       -0.00668 0.00928 11.91  -0.720  0.4857
 2,4D - Dicamba           0.00953 0.00762  8.73   1.250  0.2439
 2,4D - Glifosato         0.00206 0.01090 11.49   0.189  0.8533
 2,4D - Imazetapir       -0.01050 0.00925 11.89  -1.135  0.2789
 2,4D - Testigo          -0.00758 0.01080 11.65  -0.698  0.4986
 Clorimuron - Dicamba     0.01620 0.00711  9.18   2.280  0.0480
 Clorimuron - Glifosato   0.00874 0.01050 11.03   0.828  0.4251
 Clorimuron - Imazetapir -0.00382 0.00883 12.00  -0.433  0.6727
 Clorimuron - Testigo    -0.00090 0.01050 11.24  -0.086  0.9331
 Dicamba - Glifosato     -0.00746 0.00913  7.82  -0.817  0.4379
 Dicamba - Imazetapir    -0.02003 0.00708  9.21  -2.830  0.0193
 Dicamba - Testigo       -0.01710 0.00906  8.02  -1.888  0.0956
 Glifosato - Imazetapir  -0.01256 0.01050 11.04  -1.193  0.2579
 Glifosato - Testigo     -0.00964 0.01200 12.01  -0.806  0.4357
 Imazetapir - Testigo     0.00293 0.01050 11.17   0.279  0.7850

Results are averaged over the levels of: Condicion 
Degrees-of-freedom method: satterthwaite </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(emm_trat, <span class="at">adjust =</span> <span class="st">"holm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                estimate      SE    df t.ratio p.value
 2,4D - Clorimuron       -0.00668 0.00928 11.91  -0.720  1.0000
 2,4D - Dicamba           0.00953 0.00762  8.73   1.250  1.0000
 2,4D - Glifosato         0.00206 0.01090 11.49   0.189  1.0000
 2,4D - Imazetapir       -0.01050 0.00925 11.89  -1.135  1.0000
 2,4D - Testigo          -0.00758 0.01080 11.65  -0.698  1.0000
 Clorimuron - Dicamba     0.01620 0.00711  9.18   2.280  0.6721
 Clorimuron - Glifosato   0.00874 0.01050 11.03   0.828  1.0000
 Clorimuron - Imazetapir -0.00382 0.00883 12.00  -0.433  1.0000
 Clorimuron - Testigo    -0.00090 0.01050 11.24  -0.086  1.0000
 Dicamba - Glifosato     -0.00746 0.00913  7.82  -0.817  1.0000
 Dicamba - Imazetapir    -0.02003 0.00708  9.21  -2.830  0.2891
 Dicamba - Testigo       -0.01710 0.00906  8.02  -1.888  1.0000
 Glifosato - Imazetapir  -0.01256 0.01050 11.04  -1.193  1.0000
 Glifosato - Testigo     -0.00964 0.01200 12.01  -0.806  1.0000
 Imazetapir - Testigo     0.00293 0.01050 11.17   0.279  1.0000

Results are averaged over the levels of: Condicion 
Degrees-of-freedom method: satterthwaite 
P value adjustment: holm method for 15 tests </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(emm_trat, <span class="at">adjust =</span> <span class="st">"BH"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                estimate      SE    df t.ratio p.value
 2,4D - Clorimuron       -0.00668 0.00928 11.91  -0.720  0.6799
 2,4D - Dicamba           0.00953 0.00762  8.73   1.250  0.6799
 2,4D - Glifosato         0.00206 0.01090 11.49   0.189  0.9142
 2,4D - Imazetapir       -0.01050 0.00925 11.89  -1.135  0.6799
 2,4D - Testigo          -0.00758 0.01080 11.65  -0.698  0.6799
 Clorimuron - Dicamba     0.01620 0.00711  9.18   2.280  0.3600
 Clorimuron - Glifosato   0.00874 0.01050 11.03   0.828  0.6799
 Clorimuron - Imazetapir -0.00382 0.00883 12.00  -0.433  0.8408
 Clorimuron - Testigo    -0.00090 0.01050 11.24  -0.086  0.9331
 Dicamba - Glifosato     -0.00746 0.00913  7.82  -0.817  0.6799
 Dicamba - Imazetapir    -0.02003 0.00708  9.21  -2.830  0.2891
 Dicamba - Testigo       -0.01710 0.00906  8.02  -1.888  0.4782
 Glifosato - Imazetapir  -0.01256 0.01050 11.04  -1.193  0.6799
 Glifosato - Testigo     -0.00964 0.01200 12.01  -0.806  0.6799
 Imazetapir - Testigo     0.00293 0.01050 11.17   0.279  0.9058

Results are averaged over the levels of: Condicion 
Degrees-of-freedom method: satterthwaite 
P value adjustment: BH method for 15 tests </code></pre>
</div>
</div>
<p>Dunnet</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(modelo_gls, <span class="sc">~</span> Tratamiento) <span class="sc">%&gt;%</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">contrast</span>(<span class="at">method =</span> <span class="st">"trt.vs.ctrl"</span>, <span class="at">ref =</span> <span class="st">"Testigo"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>NOTE: Results may be misleading due to involvement in interactions</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast             estimate      SE    df t.ratio p.value
 2,4D - Testigo       -0.00758 0.01080 11.65  -0.698  0.8878
 Clorimuron - Testigo -0.00090 0.01050 11.24  -0.086  0.9996
 Dicamba - Testigo    -0.01710 0.00906  8.02  -1.888  0.2995
 Glifosato - Testigo  -0.00964 0.01200 12.01  -0.806  0.8420
 Imazetapir - Testigo  0.00293 0.01050 11.17   0.279  0.9894

Results are averaged over the levels of: Condicion 
Degrees-of-freedom method: satterthwaite 
P value adjustment: dunnettx method for 5 tests </code></pre>
</div>
</div>
</section>
<section id="conclusión-estadística" class="level2">
<h2 class="anchored" data-anchor-id="conclusión-estadística">Conclusión estadística</h2>
<p>El modelo de mínimos cuadrados generalizados evidenció que la condición tuvo un efecto significativo sobre el peso seco medio (p &lt; 0.0001). No se detectó interacción significativa entre tratamiento y condición (p = 0.3419), ni efecto del tratamiento sobre la variable en estudio (p = 0.0507)</p>
</section>
<section id="modelo-con-glmm" class="level2">
<h2 class="anchored" data-anchor-id="modelo-con-glmm">Modelo con glmm</h2>
<p>Incluyo la varainza en el modelo</p>
<p>El análisis gráfico de los residuos en función de los valores ajustados evidenció un patrón de dispersión creciente, indicando la presencia de heterocedasticidad. Por lo tanto, no se cumple el supuesto de homogeneidad de varianzas requerido por el ANOVA. tambien se obtiene un pvalore de 0.03117 en el test de hocedasticidad</p>
<p>Se debe incorporar en el modelo</p>
<p>Incluyo la varainza en el modelo</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmmTMB)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>modelo_glm <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(Peso <span class="sc">~</span> Tratamiento <span class="sc">*</span> Condicion,</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">family =</span> <span class="fu">gaussian</span>(),</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> peso)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_glm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: gaussian  ( identity )
Formula:          Peso ~ Tratamiento * Condicion
Data: peso

      AIC       BIC    logLik -2*log(L)  df.resid 
   -230.6    -206.3     128.3    -256.6        35 


Dispersion estimate for gaussian family (sigma^2): 0.000279 

Conditional model:
                                           Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)                                0.034225   0.008351   4.098 4.16e-05
TratamientoClorimuron                      0.006225   0.011810   0.527  0.59814
TratamientoDicamba                         0.001450   0.011810   0.123  0.90229
TratamientoGlifosato                      -0.006175   0.011810  -0.523  0.60107
TratamientoImazetapir                      0.012225   0.011810   1.035  0.30063
TratamientoTestigo                         0.012650   0.011810   1.071  0.28413
CondicionSin estres                        0.035000   0.011810   2.963  0.00304
TratamientoClorimuron:CondicionSin estres  0.000900   0.016702   0.054  0.95703
TratamientoDicamba:CondicionSin estres    -0.021950   0.016702  -1.314  0.18878
TratamientoGlifosato:CondicionSin estres   0.008225   0.016702   0.492  0.62239
TratamientoImazetapir:CondicionSin estres -0.003450   0.016702  -0.207  0.83637
TratamientoTestigo:CondicionSin estres    -0.010150   0.016702  -0.608  0.54340
                                             
(Intercept)                               ***
TratamientoClorimuron                        
TratamientoDicamba                           
TratamientoGlifosato                         
TratamientoImazetapir                        
TratamientoTestigo                           
CondicionSin estres                       ** 
TratamientoClorimuron:CondicionSin estres    
TratamientoDicamba:CondicionSin estres       
TratamientoGlifosato:CondicionSin estres     
TratamientoImazetapir:CondicionSin estres    
TratamientoTestigo:CondicionSin estres       
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(modelo_glm, <span class="sc">~</span> Tratamiento <span class="sc">*</span> Condicion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Tratamiento Condicion  emmean      SE df lower.CL upper.CL
 2,4D        Con estres 0.0342 0.00835 35   0.0173   0.0512
 Clorimuron  Con estres 0.0404 0.00835 35   0.0235   0.0574
 Dicamba     Con estres 0.0357 0.00835 35   0.0187   0.0526
 Glifosato   Con estres 0.0280 0.00835 35   0.0111   0.0450
 Imazetapir  Con estres 0.0464 0.00835 35   0.0295   0.0634
 Testigo     Con estres 0.0469 0.00835 35   0.0299   0.0638
 2,4D        Sin estres 0.0692 0.00835 35   0.0523   0.0862
 Clorimuron  Sin estres 0.0763 0.00835 35   0.0594   0.0933
 Dicamba     Sin estres 0.0487 0.00835 35   0.0318   0.0657
 Glifosato   Sin estres 0.0713 0.00835 35   0.0543   0.0882
 Imazetapir  Sin estres 0.0780 0.00835 35   0.0610   0.0950
 Testigo     Sin estres 0.0717 0.00835 35   0.0548   0.0887

Confidence level used: 0.95 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(<span class="fu">emmeans</span>(modelo_glm, <span class="sc">~</span> Tratamiento <span class="sc">|</span> Condicion))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Condicion = Con estres:
 contrast                 estimate     SE df t.ratio p.value
 2,4D - Clorimuron       -0.006225 0.0118 35  -0.527  0.9947
 2,4D - Dicamba          -0.001450 0.0118 35  -0.123  1.0000
 2,4D - Glifosato         0.006175 0.0118 35   0.523  0.9949
 2,4D - Imazetapir       -0.012225 0.0118 35  -1.035  0.9028
 2,4D - Testigo          -0.012650 0.0118 35  -1.071  0.8895
 Clorimuron - Dicamba     0.004775 0.0118 35   0.404  0.9985
 Clorimuron - Glifosato   0.012400 0.0118 35   1.050  0.8974
 Clorimuron - Imazetapir -0.006000 0.0118 35  -0.508  0.9955
 Clorimuron - Testigo    -0.006425 0.0118 35  -0.544  0.9939
 Dicamba - Glifosato      0.007625 0.0118 35   0.646  0.9865
 Dicamba - Imazetapir    -0.010775 0.0118 35  -0.912  0.9407
 Dicamba - Testigo       -0.011200 0.0118 35  -0.948  0.9308
 Glifosato - Imazetapir  -0.018400 0.0118 35  -1.558  0.6304
 Glifosato - Testigo     -0.018825 0.0118 35  -1.594  0.6078
 Imazetapir - Testigo    -0.000425 0.0118 35  -0.036  1.0000

Condicion = Sin estres:
 contrast                 estimate     SE df t.ratio p.value
 2,4D - Clorimuron       -0.007125 0.0118 35  -0.603  0.9901
 2,4D - Dicamba           0.020500 0.0118 35   1.736  0.5185
 2,4D - Glifosato        -0.002050 0.0118 35  -0.174  1.0000
 2,4D - Imazetapir       -0.008775 0.0118 35  -0.743  0.9750
 2,4D - Testigo          -0.002500 0.0118 35  -0.212  0.9999
 Clorimuron - Dicamba     0.027625 0.0118 35   2.339  0.2061
 Clorimuron - Glifosato   0.005075 0.0118 35   0.430  0.9980
 Clorimuron - Imazetapir -0.001650 0.0118 35  -0.140  1.0000
 Clorimuron - Testigo     0.004625 0.0118 35   0.392  0.9987
 Dicamba - Glifosato     -0.022550 0.0118 35  -1.909  0.4136
 Dicamba - Imazetapir    -0.029275 0.0118 35  -2.479  0.1582
 Dicamba - Testigo       -0.023000 0.0118 35  -1.947  0.3918
 Glifosato - Imazetapir  -0.006725 0.0118 35  -0.569  0.9924
 Glifosato - Testigo     -0.000450 0.0118 35  -0.038  1.0000
 Imazetapir - Testigo     0.006275 0.0118 35   0.531  0.9945

P value adjustment: tukey method for comparing a family of 6 estimates </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DHARMa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>This is DHARMa 0.4.7. For overview type '?DHARMa'. For recent changes, type news(package = 'DHARMa')</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">simulateResiduals</span>(modelo_glm)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="peso_seco_final_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>interpreación ks test p=0.987, no hay problema con los residuos dispersión p=0.88 no hay heterocedasticidad detectada Outlier test: p = 1 no hay valores atipocos detectados</p>
<p>El diagnóstico de residuos mediante el paquete DHARMa no evidenció desviaciones significativas respecto a los supuestos del modelo. Los residuos presentaron una distribución uniforme (KS test, p = 0.987), sin problemas de dispersión (p = 0.88) ni valores atípicos influyentes (p = 1). Asimismo, no se observaron patrones sistemáticos en función de los valores predichos. En conjunto, estos resultados indican un adecuado ajuste del modelo.</p>
<section id="conclusión-estadística-1" class="level3">
<h3 class="anchored" data-anchor-id="conclusión-estadística-1">Conclusión estadística:</h3>
<p>El análisis mediante un modelo lineal generalizado mostró que no existe efecto de interacción significativa entre tratamiento y condición sobre el peso promedia (p = 0.559), lo que indica que el efecto del tratamiento es consistente entre condiciones. El factor tratamiento no presentó efectos significativos sobre la variable peso (p = 0.563). En cambio, la condición experimental tuvo un efecto significativo sobre el peso (p = 0.003), evidenciando diferencias entre sus niveles.</p>
<p>interpreación ks test p=0.987, no hay problema con los residuos dispersión p=0.88 no hay heterocedasticidad detectada Outlier test: p = 1 no hay valores atipocos detectados</p>
<p>El diagnóstico de residuos mediante el paquete DHARMa no evidenció desviaciones significativas respecto a los supuestos del modelo. Los residuos presentaron una distribución uniforme (KS test, p = 0.987), sin problemas de dispersión (p = 0.88) ni valores atípicos influyentes (p = 1). Asimismo, no se observaron patrones sistemáticos en función de los valores predichos. En conjunto, estos resultados indican un adecuado ajuste del modelo.</p>
</section>
<section id="conclusión-estadística-2" class="level3">
<h3 class="anchored" data-anchor-id="conclusión-estadística-2">Conclusión estadística:</h3>
<p>El análisis mediante un modelo lineal generalizado mostró que no existe efecto de interacción significativa entre tratamiento y condición sobre el peso promedia (p = 0.559), lo que indica que el efecto del tratamiento es consistente entre condiciones.</p>
<p>El factor tratamiento no presentó efectos significativos sobre la variable peso (p = 0.563).</p>
<p>En cambio, la condición experimental tuvo un efecto significativo sobre el peso (p = 0.003), evidenciando diferencias entre sus niveles.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>